name: stripe_payment
description: A Flutter plugin to integrate the stripe libraries for iOS and Android. Supports Apple / Google Pay, SCA, PSD2 and much more.
version: 1.0.10

homepage: https://github.com/jonasbark/flutter_stripe_payment

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: de.jonasbark.stripepayment
    pluginClass: StripePaymentPlugin